---
driver:
  name: vagrant
  customize:
    memory: 2048

provisioner:
  name: ansible_push
  playbook: test/integration/default/oneagent.yml
  ansible_config: test/ansible.cfg
  extra_vars: "@vars.yml"
  verbose: vv
  remote_user: vagrant
  chef_bootstrap_url: nil
  environment_vars:
    OBJC_DISABLE_INITIALIZE_FORK_SAFETY: 'YES' # for Mac OSX compatibility

verifier:
  name: inspec

transport:
  max_ssh_sessions: 6

platforms:
  - name: ubuntu/xenial64
  - name: ubuntu/bionic64
  - name: generic/rhel7
  - name: generic/rhel8
  - name: windows_2012r2
    driver:
      box: tas50/windows_2012r2
      gui: false
      network:
        - ["forwarded_port", {guest: 5985, host: 5985}]
    provisioner:
      ansible_connection: winrm
      ansible_port: 5985
  - name: windows_2016
    driver:
      box: tas50/windows_2016
      gui: false
      network:
        - ["forwarded_port", {guest: 5985, host: 5985}]
    provisioner:
      ansible_connection: winrm
      ansible_port: 5985
  - name: windows_2019
    driver:
      box: tas50/windows_2019
      gui: false
      network:
        - ["forwarded_port", {guest: 5985, host: 5985}]
    provisioner:
      ansible_connection: winrm
      ansible_port: 5985

suites:
  - name: linux
    includes:
      - ubuntu/xenial64
      - ubuntu/bionic64
      - generic/rhel7
      - generic/rhel8
  - name: windows
    includes:
      - windows_2012r2
      - windows_2016
      - windows_2019
