---

# Author : DOT_STI_Supervision
# Purpose : Play to install a plugin on a Dynatrace Active Gate and in the corresponding Dynatrace Managed Tenant
# Target : Linux / Windows / AIX

- hosts: all
  vars:
  become_user: root
  tasks:
  - name: main
    include_tasks: "tasks/activegate_plugin_solace_install.yml"
