---

# Author : DOT_STI_Supervision
# Purpose : Play to uninstall a Dynatrace Active Gate on a given host
# Target : Linux / Windows / AIX

- hosts: all
  vars:
  become_user: root
  tasks:
  - name: main
    include_tasks: "tasks/activegate_uninstall.yml"
