---

# Author : DOT_STI_Supervision
# Purpose : Play to update the metatags for a given host in the corresponding tenant
# Target : Linux / Windows / AIX

- hosts: all
  vars:
  become_user: root
  tasks:
  - name: main
    include_tasks: "tasks/update_metatags.yml"
