---

# Author : DOT_STI_Supervision
# Purpose : Play to install a Dynatrace Oneagent on a given host
# Target : Linux / Windows / AIX

- hosts: all
  vars:
  become_user: root
  tasks:
  - name: main
    include_tasks: "tasks/main.yml"
