---


# Author : DOT_STI_Supervision
# Purpose : Play to install a Dynatrace Active Gate on a given host
# Target : Linux / Windows / AIX


- name: Check required variables
  fail:
    msg: "One or more required variables are not defined. Please see documentation for further information."
  when: not dynatrace_environment_url

- name: load default variables based on OS
  include_vars: "defaults/main/{{ ansible_system | lower }}.yml"

- name: load variables based on OS
  include_vars: "vars/{{ ansible_system | lower }}.yml"

- name: set url for dmz servers
  set_fact:
    dynatrace_activegate_installer_url: http://hostname.client.com/pub/packages/dot-sti-supervision-admin/dynatrace/{{ dynatrace_environment_url.split('/').2 }}/{{ dynatrace_activegate_install_url_key }}/Dynatrace-ActiveGate-Linux-latest.sh
  when: "ansible_system|lower == 'linux'"

- name: check if activegate is installed | linux
  stat:
    path: "sudo {{ dynatrace_oneagent_install_artifact }}"
  register: dynatrace_oneagent_state_file_linux
  when: ansible_system|lower == "linux"

- name: download dynatrace activegate | linux
  get_url:
    url: "{{ dynatrace_activegate_installer_url }}"
    dest: "{{ dynatrace_activegate_install_script }}"
  when: ansible_system|lower == "linux"

- name: install dynatrace active gate | linux
  command: "sudo {{ dynatrace_activegate_install_cmd }}"
  when: ansible_system|lower == "linux"
  become: true
  become_user: root
