---

# Author : DOT_STI_Supervision
# Purpose : Play to uninstall a Dynatrace Active Gate
# Target : Linux / Windows / AIX

- name: Check required variables
  fail:
    msg: "One or more required variables are not defined. Please see documentation for further information."
  when: not dynatrace_environment_url

- name: load default variables based on OS
  include_vars: "defaults/main/{{ ansible_system | lower }}.yml"

- name: load variables based on OS
  include_vars: "vars/{{ ansible_system | lower }}.yml"

- name: uninstall dynatrace active gate | linux
  command: "sudo /opt/dynatrace/gateway/uninstall.sh"
  when: ansible_system|lower == "linux"
  become: true
  become_user: root

- name: clean activegate directory
  file:
    state: absent
    path: "/opt/dynatrace/gateway/"
